services:
  cdc-client:
   build:
     context: ./cdc-client
     dockerfile: Dockerfile
   restart: always
   environment:
      JAVA_OPTS: "-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
      QUARKUS_LOG_LEVEL: INFO
      LOG_LEVEL: INFO
   ports:
     - "8081:8081"
   volumes:
     - offsets:/var/offsets
     - ./cdc-client/${PROPERTIES_TEMPLATE:-kafka-confluent-avro}.properties.template:/opt/debezium/conf/application.properties.template
     - ${GOOGLE_APPLICATION_CREDENTIALS}:/opt/debezium/credentials.json
     - ./secrets/confluent-registry.certificate.pem:/opt/debezium/confluent-registry.certificate.pem
   depends_on:
     - postgres-db

  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION:-7.8.1}
    ports:
      - "9092:9092"
      - "9093:9093"  # Internal listener
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: local
    volumes:
      - kafka-data:/var/lib/kafka/data

  confluent-registry:
    build:
      context: ./confluent-registry
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - kafka
    volumes:
    - ./confluent-registry/schema-registry.properties:/etc/schema-registry/schema-registry.properties
    - ./secrets/confluent-registry.keystore.jks:/etc/schema-registry/confluent-registry.keystore.jks
    - ./secrets/confluent-registry.truststore.jks:/etc/schema-registry/confluent-registry.truststore.jks
    ports:
    - "8080:8080"

  postgres-db:
    image: postgres:${POSTGRES_VERSION:-15.7-alpine}
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres-db/${INIT_SQL:-init.sql}:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: {}
  offsets: {}
  kafka-data: {}